version: '3'
services:
  app:
    build: .
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - TWILIO_TOKEN=example
      - TWILIO_SID=example
      - TWILIO_PH_NO=example
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user9878
      - MYSQL_ROOT_PASSWORD=user9878

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: user9878
      MYSQL_ROOT_PASSWORD: user9878
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/1.sql

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    expose:
      - "6379"
